// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace HierarchicalModelTestFunc
{
    public class HierarchicalModelTestFuncOutputs: SystemResults
    {
		/// <summary>
		/// Your fortune
		/// </summary>
		[JsonProperty("Fortune")]
		public string Fortune {get; set;}



        /// <summary>
        /// Construct a HierarchicalModelTestFuncOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public HierarchicalModelTestFuncOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a HierarchicalModelTestFuncOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public HierarchicalModelTestFuncOutputs(string fortune): base()
        {
			this.Fortune = fortune;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}